name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: apps/docs/package-lock.json
        
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "$PWD/upstream/emscripten" >> $GITHUB_PATH
        echo "EMSDK=$PWD" >> $GITHUB_ENV
        
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        
    - name: Build WebAssembly using build script
      run: |
        source emsdk/emsdk_env.sh
        chmod +x build.sh
        ./build.sh --web
        
    - name: Install web dependencies
      run: |
        cd apps/docs
        npm ci
        
    - name: Build the web app
      run: |
        cd apps/docs
        npm run build
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/docs/dist 